# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96104930ed884fd56d38da0509bab38ddc6e348c968354a1dfc54a97b8d127af7446df02c3bec1ac89a43de636879b20fbbd5612910df85a60662ae8d07a227f

test:
  secret_key_base: 4324ed2ec2245a886cbb032d268a0112554b9082a54a1f17e49f129e70be43f93531e53caae03f17b85e0ee22ac7a1fd844a6a9aa23551f61bf4716ed76036b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
